apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: php-job-demo
  labels:
    app: php-job-demo
    component: worker
spec:
  replicas: 0  # KEDA manages replica count
  selector:
    matchLabels:
      app: php-job-demo
      component: worker
  template:
    metadata:
      labels:
        app: php-job-demo
        component: worker
    spec:
      containers:
        - name: worker
          image: somesh0007/myrepo:php-job-extrdb
          command: ["php", "bin/console", "messenger:consume", "async", "--time-limit=3600"]
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
